name: base
channels:
  - conda-forge
dependencies:
  - conda
  - python=3.8
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - pyuvdata
  - pyyaml
  - scipy
  - matplotlib
  - numpy
  - attrs
